# '.github/workflows/Rbac_Apply.yml'
name: RBAC-Apply-$(Rev:rr)
on:   
  push:
    paths:
      - 'roleDefinitions/*'

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    #- name: Log into Azure using github secret AZURE_CREDENTIALS
    #  uses: Azure/login@v1
    #  with:
    #    creds: ${{ secrets.AZURE_CREDENTIALS }}
    #    enable-AzPSSession: true

    - name: 'Get changed role definitions'
      shell: powershell
      run: |
       $editedFiles = git diff HEAD HEAD~ --name-only

       $resultArray = @()
       Foreach ($file in $editedFiles) {
           if ($file -like "roleDefinitions/*") {
           $filePath = "$ {{ env.GITHUB_WORKSPACE }}\$file"
           $resultArray += $filePath
           }
       }
       Write-Output "The following role definitions have been created / changed:"
       Write-Output "$resultArray"

       #Create a useable github environment variable array to string that will be used in powershell script
       $psStringResult = @()
       $resultArray | ForEach-Object {
           $psStringResult += ('"' + $_.Split(',') + '"')
       }
       $psStringResult = "@(" + ($psStringResult -join ',') + ")"

       #Set github env variable to use in powershell script as input
       Write-Output "##vso[task.setvariable variable=roledefinitions;]$psStringResult"
       echo "ROLEDEFINITIONS=$psStringResult" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

       Write-Output "Convert array to psString:"
       Write-Output $psStringResult